# Generated by Django 2.0.13 on 2019-04-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='movie_id',
            new_name='lecture_id',
        ),
    ]
